"use client";

import { ClipboardList, Wrench, AlertTriangle, ShieldCheck, Activity, Target, Download } from "lucide-react";
import { motion } from "framer-motion";
import { jsPDF } from "jspdf"; 

interface MachineHealthReportProps {
  liveData: any; 
}

export default function MachineHealthReport({ liveData }: MachineHealthReportProps) {
  if (!liveData) {
    return (
      <div className="bg-[#160a0a] border border-red-500/20 p-6 rounded-md shadow-lg flex flex-col items-center justify-center min-h-[300px] text-gray-500">
        <ClipboardList className="w-12 h-12 mb-4 opacity-50" />
        <p className="text-xs font-mono tracking-widest uppercase text-center">
          AWAITING LIVE SCAN DATA <br/> Run S11 to generate dynamic AI health report
        </p>
      </div>
    );
  }

  const { risk_percentage, live_health, state, label, inputs } = liveData;

  let verdictIcon = <ShieldCheck className="w-5 h-5 text-green-500" />;
  if (state === "fault") verdictIcon = <AlertTriangle className="w-5 h-5 text-red-500 animate-pulse" />;
  if (state === "warn") verdictIcon = <Activity className="w-5 h-5 text-orange-500" />;

  const handleDownloadReport = () => {
    const doc = new jsPDF();
    const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
    const marginX = 14;
    let currentY = 20;

    const addSection = (title: string, content: string) => {
      if (currentY > 270) {
        doc.addPage();
        currentY = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(220, 38, 38);
      doc.text(title, marginX, currentY);
      currentY += 6;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(50, 50, 50);
      
      const splitContent = doc.splitTextToSize(content, 180);
      doc.text(splitContent, marginX, currentY);
      
      currentY += (splitContent.length * 5) + 8;
    };

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("DYNAMO MOTOR INTELLIGENCE - DIAGNOSTIC TICKET", marginX, currentY);
    currentY += 10;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`DATE GENERATED : ${timestamp}`, marginX, currentY);
    currentY += 6;
    doc.text(`STATUS VERDICT : ${label}`, marginX, currentY);
    currentY += 6;
    doc.setFont("helvetica", "bold");
    doc.text(`RISK SCORE     : ${risk_percentage.toFixed(1)}%`, marginX, currentY);
    currentY += 12;

    doc.setDrawColor(200, 200, 200);
    doc.line(marginX, currentY - 6, 196, currentY - 6);

    const formattedInputs = Object.entries(inputs || {})
      .map(([key, value]) => `• ${key.toUpperCase()}: ${value}`)
      .join("\n");

    addSection("[1] LIVE SENSOR TELEMETRY", formattedInputs || "(No telemetry data provided)");
    
    addSection("[2] PREDICTIVE ML METRICS", 
      `• ARMARTURE HEALTH INDEX: ${live_health.health_pct.toFixed(1)}%\n` +
      `• REMAINING USEFUL LIFE: ${live_health.rul_cycles.toLocaleString()} cycles (~${live_health.rul_days} days)\n` +
      `• PRIMARY FAULT DRIVER: ${live_health.top_driver.toUpperCase()}`
    );
    
    addSection("[3] AI SYSTEM ANALYSIS", live_health.summary);
    addSection("[4] ROOT CAUSE IDENTIFICATION", live_health.cause);
    addSection("[5] RECOMMENDED MAINTENANCE ACTION", live_health.remedies);

    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("END OF REPORT - GENERATED BY DYNAMO PREDICTIVE ENGINE", marginX, 285);

    doc.save(`DYNAMO_Ticket_${timestamp.replace(/[: ]/g, "_")}.pdf`);
  };

  return (
    <div className="bg-gradient-to-br from-[#160a0a] to-[#0e0606] border border-red-500/30 p-6 rounded-md shadow-[0_0_40px_rgba(220,38,38,0.08)] relative overflow-hidden">
      <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-red-600 via-orange-500 to-cyan-500" />
      
      <div className="flex items-center justify-between mb-6 pb-4 border-b border-white/5">
        <div className="flex items-center gap-3">
          <ClipboardList className="w-6 h-6 text-red-500" />
          <div>
            <h2 className="text-lg font-bold tracking-[0.2em] text-white uppercase drop-shadow-[0_0_10px_rgba(220,38,38,0.5)]">
              LIVE DIGITAL TWIN REPORT
            </h2>
            <p className="text-[10px] text-gray-400 font-mono tracking-widest uppercase mt-1">Generated by AI</p>
          </div>
        </div>
        
        <button 
          onClick={handleDownloadReport}
          className="flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-500 text-white font-bold text-[10px] tracking-[0.2em] uppercase rounded transition-all shadow-[0_0_15px_rgba(220,38,38,0.3)]"
        >
          <Download className="w-4 h-4" />
          Export PDF Ticket
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <ReportItem 
          label="Live Health Index" 
          value={`${live_health.health_pct.toFixed(1)}%`} 
          highlight={state === 'ok' ? 'text-green-500' : state === 'warn' ? 'text-orange-500' : 'text-red-500'} 
        />
        <ReportItem 
          label="Estimated RUL" 
          value={`${live_health.rul_cycles.toLocaleString()} cycles`} 
          subValue={`(${live_health.rul_days} days)`} 
        />
        <ReportItem 
          label="Active Fault Driver" 
          value={live_health.top_driver.toUpperCase()} 
          highlight="text-orange-500" 
        />
      </div>

      <div className="bg-[#0e0606] border border-white/10 p-5 rounded font-mono text-xs leading-loose text-gray-400 space-y-5">
        <div>
          <span className="text-white font-sans font-bold tracking-[0.2em] text-[11px] mb-2 flex items-center gap-2">
            <Activity className="w-3 h-3 text-cyan-500"/> SYSTEM ANALYSIS
          </span>
          <span className="text-cyan-100/70">{live_health.summary}</span>
        </div>

        <div className="pt-3 border-t border-white/5">
          <span className="text-white font-sans font-bold tracking-[0.2em] text-[11px] mb-2 flex items-center gap-2">
            <Target className="w-3 h-3 text-red-500"/> ROOT CAUSE IDENTIFICATION
          </span>
          <span className="text-red-200/70">{live_health.cause}</span>
        </div>
        
        <div className="pt-3 border-t border-white/5">
          <span className="text-white font-sans font-bold tracking-[0.2em] text-[11px] mb-2 flex items-center gap-2">
            <Wrench className="w-3 h-3 text-orange-500"/> RECOMMENDED ACTION
          </span>
          <span className="text-orange-200/70">{live_health.remedies}</span>
        </div>
      </div>

      <motion.div 
        key={state} 
        initial={{ y: 10, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        className={`mt-6 p-4 rounded border flex items-center gap-3 font-bold tracking-widest text-[13px] uppercase ${
          state === 'ok' ? 'bg-green-500/10 border-green-500/30 text-green-500' :
          state === 'warn' ? 'bg-orange-500/10 border-orange-500/30 text-orange-500' :
          'bg-red-500/10 border-red-500/30 text-red-500'
        }`}
      >
        {verdictIcon} VERDICT: {label}
      </motion.div>
    </div>
  );
}

function ReportItem({ label, value, subValue, highlight = "text-white" }: { label: string, value: string, subValue?: string, highlight?: string }) {
  return (
    <div className="bg-[#1e0f0f] border border-red-500/10 p-4 rounded relative overflow-hidden">
      <div className="text-[10px] text-gray-400 tracking-[0.15em] uppercase mb-1">
        <span className="text-red-500 mr-1">▸</span>{label}
      </div>
      <div className={`text-xl font-bold font-sans tracking-wide ${highlight}`}>
        {value} {subValue && <span className="text-xs text-gray-500 tracking-normal ml-1">{subValue}</span>}
      </div>
    </div>
  );
}